server:
  port: 8000
spring:
  application:
    name: exchange-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false


#-Dserver:port=8001: na config VM options do Startup 8001
# HeidiSQL - foo_bar -> exchange e exchange_service